#!/usr/bin/env python3
"""Regenerate every paper artifact from the current results in one shot.

    PAPER_ROOT=/path/to/HypergraphMISReduction-Paper python3 make_all_paper.py

Steps:
  1. write tikz/plotcolors.tex (central \\definecolor for every fragment colour),
  2. run every make_*.py generator (each emits its \\input fragments into the paper),
  3. bake tables/tables_reduced.tex (the per-instance Table A.2) from the reduction
     runs -- static rows, no compile-time TSV parsing.

Individual scripts can also be run on their own; this is just the convenience
wrapper. Re-running is idempotent: fragments are overwritten in place.
"""

import csv
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from paper_plot_common import (  # noqa: E402
    RESULTS_DIR,
    PAPER_ROOT, REPO_LATEX_ROOT, add_class_prefix, min_by_graph, tab_path,
    write_plot_colors,
)

# The reproducibility document (latex/main.tex) \inputs every fragment in this
# order; each entry is (relative path under the output root, section heading).
# Only written when the output root IS the repo's latex/ tree -- we never drop a
# main.tex into the actual paper checkout.
REPRO_DOC_FRAGMENTS = [
    ("tables/reduction_effect.tex", "Reduction effect on instance size (tab:reduction_effect)"),
    ("tables/ablation.tex", "Per-rule ablation (tab:ablation)"),
    ("tables/strategies.tex", "Reduction and solving cost per strategy (tab:strategies)"),
    ("figures/neighborhood_mem.tex", "Neighborhood strategies time--memory (fig:neighborhood-mem)"),
    ("figures/solver_plots.tex", "Performance profiles and cactus plots (fig:solverplots)"),
    ("tables/tables_reduced.tex", "Per-instance reduction overview (tab:reductions_overview)"),
    ("tables/solvers.tex", "Full per-instance solver results (tab:overview)"),
]

# Generators to run (order irrelevant -- each writes independent fragments).
SCRIPTS = [
    "make_reduction_effect.py",
    "make_reduction_tables.py",
    "make_neighborhood_memory.py",
    "make_strategy_table.py",
    "make_solver_table.py",
    # make_perf_profiles.py + make_cactus.py are now imported as panel libraries
    # by make_solver_plots.py, which emits the combined figure (fig:solverplots).
    "make_solver_plots.py",
]

# Raw tsv files that the paper's datatool tables \DTLloaddb directly, copied
# verbatim (no transformation) into the paper so the tables read straight from
# them. (graph,algo,n,m,e,rn,rm,re,offset,time,seed,mem)
TSV_COPIES = []


def _blowup_fmt(ratio):
    """Blow-up factor as a string with two decimals (empty for N/A), matching the
    other numeric columns of Table A.2 (\\dtlround to 2 places)."""
    if ratio is None:
        return ""
    return f"{ratio:.2f}"


# Header/footer of Table A.2 (tab:reductions_overview); only the row body is
# baked from the data (see below).
_RED_TABLE_HEADER = r"""% Auto-generated by make_all_paper.py -- do not edit.
{\scriptsize
\setlength{\tabcolsep}{3pt}
\renewcommand{\arraystretch}{0.86}
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}lrrrrrrrrrr@{}}
              & \multicolumn{4}{c}{Original}
              &                 & \multicolumn{5}{c}{\strongeduced}   \\
              \cmidrule{1-5} \cmidrule{7-11}
                          & $n$       & $m$       & $\bar e$   & $b$
              &           & $n_r$     & $m_r$     & $\bar e_r$ & $b_r$      & \tred{d} [s]    \\
              \cmidrule{1-5} \cmidrule{7-11}
"""
_RED_TABLE_FOOTER = "       \\end{tabular*}}\n"


def _texname(s):
    """Escape the TeX-special characters that occur in instance display names."""
    for a, b in (("\\", r"\textbackslash "), ("_", r"\_"), ("&", r"\&"),
                 ("%", r"\%"), ("#", r"\#"), ("$", r"\$")):
        s = s.replace(a, b)
    return s


def _bake_reductions_table(rows, min_time):
    """Render tab:reductions_overview as literal rows (seed-1 sizes, min-of-k time).

    Reproduces the datatool row template exactly: \\numprint integers, two-decimal
    edge sizes, and a dash for an empty blow-up or an emptied reduced kernel."""
    def npint(x):
        return f"\\numprint{{{int(round(float(x)))}}}"

    def f2(x):
        return f"{float(x):.2f}"

    body = []
    prev_cls = None
    for r in rows:
        if r.get("seed") != "1":
            continue                                   # sizes are seed-independent
        # A little vertical space between graph classes (the class is the prefix
        # of the class-first label, e.g. dac2012 / ispd98 / sat14 / ssmc).
        cls = r["label"].split("_", 1)[0]
        if prev_cls is not None and cls != prev_cls:
            body.append("       \\addlinespace[4pt]")
        prev_cls = cls
        blow = f"\\numprint{{{r['blow']}}}" if r.get("blow") else "--"
        rblow = f"\\numprint{{{r['rblow']}}}" if r.get("rblow") else "--"
        try:
            rm_zero = int(round(float(r["rm"]))) == 0
        except (KeyError, ValueError):
            rm_zero = False
        re_cell = "--" if rm_zero else f2(r["re"])
        t = min_time.get(r["graph"])
        t_cell = f2(t) if t is not None else "--"
        # Class first, then the instance name, separated by a space instead of '_'.
        _cls, _, _rest = r["label"].partition("_")
        label = _texname(_cls) + (" " + _texname(_rest) if _rest else "")
        body.append(
            f"       {label} & {npint(r['n'])} & {npint(r['m'])}"
            f" & {f2(r['e'])} & {blow} & \\hspace*{{0.2cm}}"
            f" & {npint(r['rn'])} & {npint(r['rm'])} & {re_cell} & {rblow}"
            f" & {t_cell} \\\\")
    return _RED_TABLE_HEADER + "\n".join(body) + "\n" + _RED_TABLE_FOOTER


def build_reductions_table_source():
    """Bake tables/tables_reduced.tex, Table A.2 (tab:reductions_overview).

    Writes literal table rows, so no data file is read at pdflatex time (the
    former datatool \\DTLforeach reparsed the 75-row TSV on every pass, ~29 s each).

    The table's instance columns come from the on-demand reduction runs
    (results/RED/fred.tsv).  To those we append two clique-expansion blow-up
    columns, taken as a FACTOR from results/RED/clique.tsv (never its time or
    memory):
        blow  = gm  / m     edges after clique-expanding the ORIGINAL instance,
                            per hyperedge (a property of the input; config free)
        rblow = rgm / rm    the same for the REDUCED kernel

    clique.tsv must reduce with the same configuration as fred, or its reduced
    kernel -- and hence rgm/rm -- describes a different instance than the table's
    other reduced columns.  We therefore trust rblow only where clique.tsv's
    kernel (rn, rm) matches fred's on that instance; otherwise it is left blank
    and the table prints a dash instead of a misleading number.  The original
    blow-up does not depend on the reduction, so it is always filled when present.
    """
    fred = os.path.join(RESULTS_DIR, "RED", "fred.tsv")
    clique = os.path.join(RESULTS_DIR, "RED", "clique.tsv")
    if not os.path.exists(fred):
        print(f"[warn] missing {fred}; Table A.2 not updated")
        return

    cq = {}
    if os.path.exists(clique):
        with open(clique) as f:
            for r in csv.DictReader(f, delimiter="\t"):
                cq.setdefault(r["graph"], r)   # blow-up is seed-independent
    else:
        print(f"[warn] missing {clique}; blow-up columns left blank")

    with open(fred, newline="") as f:
        rows = list(csv.DictReader(f, delimiter="\t"))
    if not rows:
        print(f"[warn] {fred} is empty; Table A.2 not updated")
        return

    n_blow = n_rblow = n_guard = 0
    for r in rows:
        # Display name: the raw instance name shortened to the part before the
        # first dot, prefixed with its graph class (ssmc added where missing).
        r["label"] = add_class_prefix(r["graph"].split(".")[0])
        r["blow"] = r["rblow"] = ""
        c = cq.get(r["graph"])
        if not c:
            continue
        try:
            # Both the numerator (gm/rgm) and the denominator (m/rm) of the
            # blow-up come from clique.tsv, so b is computed entirely within the
            # clique-expansion run rather than mixing in fred's edge counts.
            m, rm = float(c["m"]), float(c["rm"])
            gm, rgm = float(c["gm"]), float(c["rgm"])
        except (KeyError, ValueError):
            continue
        if m > 0 and gm >= 0:
            r["blow"] = _blowup_fmt(gm / m)
            n_blow += 1
        kernel_matches = c.get("rn") == r["rn"] and c.get("rm") == r["rm"]
        if rm > 0 and rgm >= 0 and kernel_matches:
            r["rblow"] = _blowup_fmt(rgm / rm)
            n_rblow += 1
        elif rm > 0 and not kernel_matches:
            n_guard += 1

    # Sort alphabetically by the class-prefixed display name (seed as tiebreaker
    # so an instance's rows stay together); the table displays them in this order.
    rows.sort(key=lambda r: (r["label"].lower(), r["graph"], int(r.get("seed", 0))))

    # Bake the table into tables/tables_reduced.tex (was a datatool \DTLforeach
    # reparsing results/RED/fred.tsv on every pdflatex pass, ~29 s each).
    min_time = min_by_graph(rows, "time")
    with open(tab_path("tables_reduced.tex"), "w") as f:
        f.write(_bake_reductions_table(rows, min_time))
    n_table = sum(1 for r in rows if r.get("seed") == "1")

    msg = (f"baked tables/tables_reduced.tex ({n_table} rows): "
           f"{n_blow} original, {n_rblow} reduced blow-ups")
    if n_guard:
        msg += (f"; {n_guard} reduced blanked (clique.tsv kernel != fred -- "
                f"regenerate clique.tsv with the fred reduction config, -d -r9)")
    print(msg)


def write_reproducibility_doc(root):
    """Write ``main.tex``: a standalone document that \\inputs every generated
    fragment, so the repository builds all figures/tables into one PDF.

    Only the fragment list is dynamic (missing fragments are skipped); the
    packages and macros live in the static ``preamble.tex`` next to it.  Called
    only when `root` is the repo's own latex/ tree, never the paper checkout.
    """
    lines = [
        r"% Auto-generated by make_all_paper.py -- do not edit.",
        r"% Build:  cd latex && latexmk -pdf main.tex",
        r"\documentclass[10pt]{article}",
        r"\input{preamble.tex}",
        r"\begin{document}",
        r"\begin{center}",
        r"  {\Large\bfseries HyperMIS -- Reproducible Figures and Tables}\\[3pt]",
        r"  \small Generated from \texttt{results/} by \texttt{make\_all\_paper.py}.",
        r"\end{center}",
        r"\vspace{1em}",
        "",
    ]
    written = []
    for rel, title in REPRO_DOC_FRAGMENTS:
        if not os.path.exists(os.path.join(root, rel)):
            print(f"[warn] repro doc: missing {rel}, skipped")
            continue
        written.append(rel)
        lines += [
            f"\\section*{{{title.replace('_', r'\_')}}}",
            f"\\input{{{rel}}}",
            r"\clearpage",
            "",
        ]
    lines += [r"\end{document}", ""]
    with open(os.path.join(root, "main.tex"), "w") as fh:
        fh.write("\n".join(lines))
    print(f"wrote latex/main.tex ({len(written)} fragments)")


def main():
    print(f"PAPER_ROOT = {PAPER_ROOT}")

    colors = write_plot_colors()
    print(f"wrote {os.path.relpath(colors, PAPER_ROOT)}")

    env = dict(os.environ, PAPER_ROOT=PAPER_ROOT)
    failures = []
    for s in SCRIPTS:
        path = os.path.join(HERE, s)
        if not os.path.exists(path):
            print(f"[skip] {s} (not found)")
            continue
        print(f"--- {s} ---")
        r = subprocess.run([sys.executable, path], env=env)
        if r.returncode != 0:
            failures.append(s)

    dest_dir = os.path.join(PAPER_ROOT, "data", "plot_data")
    os.makedirs(dest_dir, exist_ok=True)
    for src, name in TSV_COPIES:
        src_path = os.path.join(HERE, src)
        if os.path.exists(src_path):
            shutil.copyfile(src_path, os.path.join(dest_dir, name))
            print(f"copied {src} -> data/plot_data/{name}")
        else:
            print(f"[warn] missing tsv, table will not update: {src}")

    # Bake Table A.2 from results/RED/fred.tsv + clique-expansion blow-up columns.
    build_reductions_table_source()

    # In repo mode (default output = repo latex/), emit the master document that
    # \inputs every fragment.  Never written into an actual paper checkout.
    if os.path.abspath(PAPER_ROOT) == os.path.abspath(REPO_LATEX_ROOT):
        write_reproducibility_doc(PAPER_ROOT)

    if failures:
        print(f"\nDONE with {len(failures)} script failure(s): {', '.join(failures)}")
        sys.exit(1)
    print("\nAll paper artifacts regenerated.")


if __name__ == "__main__":
    main()
