#include "config.h"

size_t VERBOSE = 0;
size_t EXPERIMENT = 0;
size_t REDUCE = 1;

size_t TIME_KERNEL_SECONDS = 100;
size_t NEIGHBORS_SIZE = 50;
size_t NUM_REMOVED_EDGES = 1000000;
size_t ITERATIONS_UNCONFINED = 20000;
size_t CONSTANT_UNCONFINED = 5;
size_t EDGE_SIZE = 5000;
size_t TWIN_NEIGHBORHOOD = 50;
size_t SUNFLOWER_NEIGHBORHOOD = 50;

size_t USE_NEIGHBORHOOD_ARRAY = 0;